### ISSUE TITLE
How do I tell if fiber finished?

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/jsfbp#1]
@bjouhier  Probably dumb question.  As I understand it, each 'run' call will run until the code returns, or until a 'yield' occurs - my question is how do I tell the difference between these two cases?  Of course, I may not have understood correctly.  Thanks!

**Comment by bjouhier** [comment]
Yes, that's right. I usually track that with a special variable. For example the `yielded` variable in https://github.com/Sage/streamlinejs/blob/master/lib/fibers/runtime.js#L175-213

**Comment by jpaulm** [comment]
@bjouhier That makes sense!  Thanks for getting back to me so fast!  Regards, P.
