### ISSUE TITLE
Travis broken in Oct. 25 this year - commit 44bd142

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/jsfbp#107]
Travis seems to be broken as of 44bd142. As far as I can see the only change was to the eslint version!

Any ideas, @comfreek?

Best regards, and season's greetings!

**Comment by ComFreek** [comment]
Hey Paul,

have a look at the Travis site:

- https://travis-ci.org/jpaulm/jsfbp
- in particular the first upper build (you've got "two builds run on every build"): https://travis-ci.org/jpaulm/jsfbp/jobs/615992765

It seems to be a node-fiber issue. In fact I guess it even is tried to be recompiled. Didn't node-fiber provide precompiled binaries for most distros? Perhaps not anymore for the distro of that build. i'd share the second link with the node-fiber community.

**Comment by jpaulm** [comment]
Hi Marcel,  thanks for getting back to me so promptly, and for pointing me
at the Travis log!  I don't know where the node-fibers community is, or
indeed if there is one, so I have posted the link you gave me to
StackOverflow.  We'll see what they come up with!

Hope everything is going well with you, and wishing you all the best for
the season!

Cheers,

Paul

**Comment by jpaulm** [comment]
Merci Marcel!  I seem to be zeroing in on the problem...  If worse comes to
worst, I will pass it over to the other Marcel!

All the best,

Paul

**Comment by ComFreek** [comment]
> I don't know where the node-fibers community is

For OSS projects a good guess is always the issue tracker: https://github.com/laverdet/node-fibers. File an issue there, I doubt someone takes a look at your StackOverflow post. It lacks a bit of research and thus is generally looked down upon in the StackOverflow community. The issue tracker is the right place, definitely, I'd say.

**Comment by jpaulm** [comment]
I was actually going starting to post an issue to Marcel Laverdet's issue tracker, but saw that he recommends checking the version of node-fibers, and found that mine was out-of-date  Not sure why renovate didn't pick up on that, but at least Travis did!  Thanks for the good tips, and Season's greetings to you and your family!

**Comment by ComFreek** [comment]
Very good to hear you got this resolved!
