### ISSUE TITLE
Reader should fail in case the file cannot be opened

### ISSUE THREAD

**Issue by ComFreek** [jpaulm/jsfbp#11]
File: `components/reader.js`
Use the `err` parameter passed to the callback:

```
fs.readFile(path, options, function(err, data) {
```

**Comment by jpaulm** [comment]
Done!

**Comment by ComFreek** [comment]
This raises also an important question: how should we handle errors in general? Throw exceptions? Pass them forth to other components?

How did you handle this topic in JavaFBP?
