### ISSUE TITLE
Reestablishing a fibre in a callback

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/jsfbp#2]
@bjouhier  Sorry to keep bothering you, but I'm a bit confused about running a callback under a fibre - not even sure if that's the right terminology!

I had my test case with the asynchronous reader working (I thought), but when I tried a more complex case (fbptest2), I found that the callback wasn't picking up the original fibre.  I now seem to have gotten it working - with some added logic in reader.js, and some more functions in fbp.js, but I just wanted to ask what controls the fibre's lifetime?  I seem to have been able to reconnect to my original fibre from the callback, using Fiber.current = xxx, but I don't know how that works under the covers!  

Hope this makes sense!  I'd like to be a bit more comfortable with what I've done!

Best regards, and thanks for all your help!

Paul

**Comment by bjouhier** [comment]
Nomally you start your fiber with:
```javascript
Fiber(function fiberBody() {
  // your code
}).run();
```
The lifetime is the fiber is tied to the execution of `fiberBody`. `fiberBody` may yield several times but it will eventually return and at that time there is not much you can do with the fiber.

`Fiber.current` points to the expected fiber when you are in `fiberBody` or in one of the functions that is called by `fiberBody`. But you should not use it inside an I/O callback because I/O callbacks are called by node's event loop, not by `fiberBody`. If you need it inside a callback you should use a closure (capture `Fiber.current` into a variable in scope which is invoked by `fiberBody`.

**Comment by jpaulm** [comment]
Your first paragraph is what I would expect to happen...  so I don't understand why my Reader module works! I am using the two-layer callback you suggested earlier, which I confess looks a bit like a closure to me! 

I guess what perplexes is me is that Reader.js definitely "ends" after the call to myReadFile(), but the callback is able to pick up the same fiber later (although not under a "run" segment).  Have I somehow created a closure?! 

When you get a chance I would very much appreciate it if you could look at https://github.com/jpaulm/jsfbp/blob/master/script/reader.js , and tell me how you would change it.  I think it's pretty self-explanatory.  Help would be much appreciated!

**Comment by jpaulm** [comment]
Hi @bjouhier, I think I have written my first closure!  I decided to start a new fibre for the callback, and, to my surprise, it seems to work!   It would still be great if, when you get a chance, you could look at https://github.com/jpaulm/jsfbp/blob/master/script/reader.js and say whether it could have been done more elegantly!  setCurrentProc has been modified (in fbp.js) to save the old Process reference, and start a new Fibre using the old Process and the code in the function... seems to work (fingers crossed)!

**Comment by jpaulm** [comment]
Reader had the "var proc" in the wrong place - it has been changed to be a parameter to the callback.

**Comment by bjouhier** [comment]
I see that you are assigning `Fiber.current` (https://github.com/jpaulm/jsfbp/blob/master/script/fbp.js#L92). I did not know that this was possible and I don't know what the consequences are. It may explain why your fiber does not have the usual lifetime.

I would expect every stream to be handled in its own fiber. A fiber may yield to itself but it should not try to transfer control to another fiber (by reassigning `Fiber.current` and yielding just after). Instead, it should just let node's event loop transfer the control.

**Comment by bjouhier** [comment]
I looked at the reader code but I find it a bit complex. I would encapsulate the whole callback handling inside a single function instead:
```
function myReadFile(path, encoding) {
  var fiber = Fiber.current;
  fs.readFile(path, encoding, function(err, data) {
    if (err) fiber.throwInto(err);
    else fiber.run(data);
  });
  return Fiber.yield();
}
```
But this assumes that you are not transferring control explicitly between fibers.

**Comment by jpaulm** [comment]
Re assigning a value to Fiber.current, that was well-spotted!  Actually that was a left-over from an earlier attempt!  I have removed it. 

I now let the callback trigger a new Fiber, and this works much better - and I don't think it violates any rules. (?)

I will also take a look at your suggested callback handling, and try to incorporate it in my code (which I agree is over-complex)!  Thanks for the good feedback!

**Comment by jpaulm** [comment]
Took a subroutine layer out of Reader.js.  Not sure if I dare make your changes, but the latest version works and it looks quite a bit cleaner!  Thanks!  Also, in my architecture I don't have any "yield"s or "run"s in components - that may be non-standard, but it matches the architecture of all my other "classical" FBP implementations. 

Onwards and upwards!

**Comment by jpaulm** [comment]
Hi, @bjouhier, I think I can close this issue.  If I don't hear any cries of protest over my revised design for Reader during the next couple of days, I will close this issue.  The Reader module is at https://github.com/jpaulm/jsfbp/blob/master/script/reader.js - and I think you have already found fbp.js.  The basic idea is to start a new fiber within the callback - using a subroutine called setProcCallback - maybe not the most self-explanatory name... 

BTW I have converted 'send', 'receive', 'create' and 'drop' into methods of various classes.  I think it's a bit more OO-like...  Hopefully it will be easier to find one's way around!

**Comment by jpaulm** [comment]
@bjouhier  I have changed 'setProcCallback' to 'queueProcCallback' as I think it is a bit more self-explanatory.  This will be used by any asynchronous (from a JS point of view) components - currently the only one so far is 'reader'.  I will assume you are OK with this, and will close this issue.

Many thanks for all your help, and good insights!

Regards,

Paul

**Comment by jpaulm** [comment]
@bjouhier Hi Bruno, I finally understood your code for my Reader and my adaptation of it seems to work!  It seems I was confused about how callbacks and fibers work together.  As they say, "the proof of the pudding etc.", so I think I've got it now.

I'm pretty excited about the potential of JSFBP, so any time you have to take a look at it and suggest potential problems, improvements, etc., would be highly appreciated!

Marcel, that goes for you too - JSFBP could vastly expand the usage of code-fibers if it catches on!

/cc @laverdet

**Comment by jpaulm** [comment]
We have opened a topic on the FBP Google Group for JSFBP - https://groups.google.com/forum/#!topic/flow-based-programming/VPBr_z2wl3k .  Any comments there (or here) would of course be welcome.  Thanks again!
