### ISSUE TITLE
Process state

### ISSUE THREAD

**Issue by kenhkan** [jpaulm/jsfbp#24]
@jpaulm @tlrobinson @ComFreek 

What do you guys think about how local state should be handled? It seems like the current JSFBP only allows "pure" processes. If you save the state outside of the scope of the `module.exports` function it becomes a singleton process.

I'm thinking it could be something like this, in pseudo-JS:

```js
module.exports = function count () {
  var proc = getProcess();
  var inport = openInputPort('in');
  var count = proc.getState('count');

  while (true) {
    var ip = receive();
    if (ip === null) {
      break;
    }

    count++;
    proc.putState('count', count);
    send(newIP(count));
  }
};
```

Any idea or previous syntax that I'm not aware of for handling local states?

**Comment by ComFreek** [comment]
I am afraid I am unable to see why normal variables inside the `count` function cannot be used.

**Comment by kenhkan** [comment]
Because it would be local to the function, so state can't be carried across process activations. Imagine you have a long-running graph with a web server. `count` would return after a request has been fulfilled so it couldn't, say, count the number of requests since the graph started.

**Comment by tlrobinson** [comment]
I assume you're referring to the "non-looper" style components?

**Comment by kenhkan** [comment]
@tlrobinson Yes, though with the current convention there is no such thing as a looper. The `while (true) { ... }` construct doesn't make it a looper in the traditional sense. When there is no more IPs to receive, the function has to quit at some point. So "loopers" and non-loopers alike can't currently keep state across activations.

**Comment by tlrobinson** [comment]
Isn't this style a "looper"? https://github.com/jpaulm/jsfbp/blob/master/components/copier.js

**Comment by kenhkan** [comment]
My apology everyone. My brain short-circuited. I kept thinking in terms of idiomatic es5. This wouldn't be a problem with es6 generators. For anyone who's interested, I seem to be able to get it to work with [es6 generator syntax](https://gist.github.com/kenhkan/c556648984ef9207658d). Closing this issue now.
