### ISSUE TITLE
The dog that didn't bark

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/jsfbp#32]
Test network `testsubstreamsensitivesplitting.js` should stop with a deadlock when the connection capacities are set to a small number - strangely enough, it doesn't, although the same network in JavaFBP and C#FBP (preemptive multithreading) does.

Challenge to the reader: why doesn't it deadlock?  TIA

**Comment by jpaulm** [comment]
It now appears that the deadlocks we were getting for this case in JavaFBP and C#FBP _may_ have been due to programming bugs.  I still wouldn't trust it, though, as it is still an example of the divergent-convergent topology.   Perhaps some kind soul might undertake to do some analysis of this situation...

**Comment by dancrumb** [comment]
FWIW: fbptest07 fails with a deadlock (as expected)... does that make you feel better? :)

**Comment by jpaulm** [comment]
Thanks!  Much better! Shall we close it?

**Comment by dancrumb** [comment]
Done!
