### ISSUE TITLE
Not keen on 2nd parameter of defProc function in Network.js

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/jsfbp#35]
If you look at https://github.com/jpaulm/jsfbp/blob/master/examples/update_c.js , you will see 3 occurrences of the `reader.js` component.  The 2nd parameter of the `defProc` calls seems to be there just to produce meaningful list items in the trace log, if one is requested.  OTOH it means thinking up what is really a 3rd name for the process.  I would suggest that the name simply be generated using `func` plus a number, thus removing the requirement for a 2nd parameter on `defProc`.  Comments, anyone?

**Comment by dancrumb** [comment]
I'm not sure that all functions have a name property in JavaScript, since it supports anonymous functions.

Perhaps you could support name templates a little bit like the old C function mktmp (http://linux.die.net/man/3/mktemp)... Just not quite so restrictive.

**Comment by dancrumb** [comment]
I was able to confirm my first point from the `node` REPL:

```
$ node
> var foo = function a(){}
undefined
> foo.name
'a'
> var bar = function(){}
undefined
> bar.name
''
```

Anonymous functions do, indeed, have no name, so they can't be relied upon for naming Processes.

I'm going to create a speculative PR for a possible solution to this.

**Comment by jpaulm** [comment]
Just curious - why?!

**Comment by dancrumb** [comment]
I closed it by accident... i meant to close the PR
