### ISSUE TITLE
Add to npm

### ISSUE THREAD

**Issue by dancrumb** [jpaulm/jsfbp#36]
What are your thoughts about adding this to the Node Package Manager system, so that folks can use it that way.

I know that npm supports adding dependencies directly from github, but a distribution version of this would be great!

I'm more than happy to do the legwork here.

**Comment by jpaulm** [comment]
Good to hear from you, Dan!  It would be great if you could add jsfbp to npm - you sound like you're familiar with all these arcane tools!  Does npm have a way of publicizing new packages?

Have you used jsfbp - if so, did it hold up, and what enhancements do you see it needing?  It has been a point of frustration for me that I hear all these js gurus saying we can never get a JS tool accepted that relies on multiple stacks (via fibers), whereas I feel this results in _much_ simpler (and more like "classical" FBP) JS FBP implementations!

Can I add you as a contributor?

Regards,

Paul

**Comment by dancrumb** [comment]
Great! I'm working on a pull request.

Since you don't know me, let me just say that I am not precious about my code, so please be direct about your feedback... I can take it :)

I am just getting into jsfbp. I tinkered with noflo but was frustrated about their bias towards coffeescript (to the point of not including JS examples in places).

As an ex-firmware developer, I actually really like fibers (as opposed to threads). The ability to multiplex without worrying so much about pre-emption is great!

You can certainly add me as a contributor (I actually did that in my update to `package.json`

I'll be creating a few more issues for questions and bug reports. Hope that's OK!

**Comment by jpaulm** [comment]
Hi Dan,

I really have to reeducate myself on jsfbp!  I have merged both your PRs,
and added you as a collaborator - although it seems that this isn't really
necessary as it looks like anyone can edit jsfbp... is this OK?

Feel free to go ahead with enhancements, bug fixes, etc.!

Cheers,

Paul M.

PS Why would the JS community resist fibers?!

**Comment by dancrumb** [comment]
And lo! it was so: https://www.npmjs.com/package/jsfbp

**Comment by jpaulm** [comment]
That's amazing!  Thanks a million!

Best regards,

Paul

**Comment by jpaulm** [comment]
Sorry, Dan, Marcel, I have just destroyed the copy of jsfbp on my C drive,
and my Readme instructions don't seem to work any more!  I run Win7.   It
started because I couldn't get access to .git/FETCH_HEAD after upgrading
posh_git...  Someone suggested deleting it, but that doesn't seem to help!

Could one of you take a look at the readme, and see what is going wrong?

TIA

PS Pls ignore title of this note

**Comment by dancrumb** [comment]
I just created #42 to track this
