### ISSUE TITLE
Following README on Win 7 doesn't work

### ISSUE THREAD

**Issue by dancrumb** [jpaulm/jsfbp#42]
Trying to get started on Win 7 by following the README does not work.

What gives?

**Comment by dancrumb** [comment]
So, I know you're using posh-git and that you're doing a clone.

Can you provide a cut and paste from your terminal showing commands and results from the git clone through to the error you're seeing?

**Comment by dancrumb** [comment]
Also, what version of node are you on?

**Comment by jpaulm** [comment]
Right now, nothing much works!  node -v says v0.12.7

There is no .git directory in my jsfbp folder.

Doing npm install jsfbp gives

C:\Users\Paul\Documents\GitHub>npm install jsfbp
npm WARN engine jsfbp@0.1.0: wanted: {"node":"~4.3.1"} (current:
{"node":"0.12.7
","npm":"2.11.3"})

The current nodejs download is v4.4.5 - would it be OK to use this?  I'm
out of time tonight - will try tomorrow.

Thanks!

**Comment by dancrumb** [comment]
Running `npm install jsfbp` won't generate a `.git` directory as it's not quite the same. For one thing, the JSFBP module doesn't include `test` or `examples` directories. Think of it more as a deployment package.

In addition, while `npm` _can_ pull from github, it's not a git client, so it doesn't pull git index information and it doesn't generate a repository

`git clone` will pull down the full development set of files that are in github; it will also generate the local repo for you and connect it to this github repository.

**Comment by dancrumb** [comment]
As for the node version, I've updated `package.json` to prevent the complaints. I don't see any reason to not to support v0.12.7.

**Comment by jpaulm** [comment]
I have downloaded the latest Node and things look a bit healthier, but when
I try cloning jsfbp I get

C:\Users\Paul\Documents\GitHub>git clone https://github.com/jpaulm/jsfbp
Cloning into 'jsfbp'...
C:/Users/Paul/Documents/GitHub/jsfbp/.git: Permission denied
Deletion of directory 'jsfbp' failed. Should I try again? (y/n) y
Deletion of directory 'jsfbp' failed. Should I try again? (y/n) y
Deletion of directory 'jsfbp' failed. Should I try again? (y/n) n

Does this make any sense?

TIA

**Comment by jpaulm** [comment]
Log of my latest attempt using https clone...  Hellpp!
[GitHubLog.txt](https://github.com/jpaulm/jsfbp/files/287879/GitHubLog.txt)

**Comment by jpaulm** [comment]
Hi Dan,

Methinks this is due to BitDefender ant-ransomware software!  It gives me a lot of trouble when using Git, but I didn't think it would block access altogether!  :-(  

Sorry for wasting your time - I'll start going through the changes/ looking at the issues tomorrow.

Thanks again and apologies!

**Comment by jpaulm** [comment]
Could you do me a favour and revise the install instructions...  and maybe add a warning about BiDefender!  :-)  BTW I did an `npm install jsfbp`, but I'm not sure what it did!

**Comment by dancrumb** [comment]
Looks like you addressed the BitDefender readme update, so i'll close this.
