### ISSUE TITLE
Employ a unit testing framework

### ISSUE THREAD

**Issue by ComFreek** [jpaulm/jsfbp#7]
For example [Mocha](http://mochajs.org/) or any other JS unit testing framework.

**Comment by tlrobinson** [comment]
I believe this can be closed, since we've got mocha set up now.

**Comment by jpaulm** [comment]
Agree!  OK @comfreek?

**Comment by tlrobinson** [comment]
Also I'd like to setup https://travis-ci.org/ to automatically run the tests when we push to GitHub.

@jpaulm could you sign up at https://travis-ci.org/ and enable it for the jsfbp repository? I can create the required `.travis.yml` file once you do that. Alternatively if you add me as a collaborate here I can do it myself: https://github.com/jpaulm/jsfbp/settings/collaboration

**Comment by ComFreek** [comment]
:+1: for Travis. @jpaulm It will display a notification about the build status (did all tests pass?) in every PR. You can see it in action here: https://github.com/discourse/discourse/pull/3202 (scroll to the bottom)

**Comment by jpaulm** [comment]
How do I set the various authorizations - e.g. my email addresses?

Regards,

Paul

**Comment by ComFreek** [comment]
@jpaulm Have you read the [Getting started guide](http://docs.travis-ci.com/user/getting-started/) (scroll down to the end of the list of languages first) and [the guide on how to set up Node.js projects](http://docs.travis-ci.com/user/languages/javascript-with-nodejs/)? I've never set up Travis CI myself, so I cannot help you except for providing links to articles.

**Comment by dancrumb** [comment]
Opened #43 for Travis CI
